// --- dialogue.js ---

export const machineReactions = {
  healing: [
    "The planet stabilizes. Briefly.",
    "You corrected something… barely.",
    "A fragile balance returns.",
    "Life finds a way. For now.",
    "The wounds close. Most of them.",
    "The planet breathes easier.",
    "Hope, against all odds.",
    "You bought some time.",
    "The scars fade, slightly.",
    "Nature adapts. It always does.",
    "A small mercy in the dark.",
    "The tides retreat. Calm returns.",
    "Something went right for once.",
    "Don't get used to it.",
    "The universe allows this.",
  ],
  fatigue: [
    "That word is tired.",
    "You've used that one too much.",
    "It's losing meaning.",
    "The word resists you now.",
    "Even words need rest.",
    "It's worn thin.",
    "Less power now.",
    "You've drained it.",
  ],
  
  destruction: [
    "You moved the moon. Half the population is gone.",
    "That was not subtle.",
    "You're learning. Unfortunately.",
    "The planet will remember this.",
    "Some things can't be undone.",
    "The screams are silent from here.",
    "Another city falls.",
    "You did that. Own it.",
    "The ground rejects what was built.",
    "Progress? Regression? Both?",
    "Life was here. Now it isn't.",
    "The ashes settle.",
    "Cause and effect. You're the cause.",
    "History will judge you. I already am.",
    "The planet weeps. Do you hear it?",
  ],
  
  weird: [
    "Reality shifted. It resisted.",
    "Something noticed.",
    "You shouldn't have done that.",
    "The universe blinked.",
    "That was not supposed to happen.",
    "The laws bend. They don't break.",
    "Paradox detected. Ignoring.",
    "Space hiccups.",
    "That echo wasn't yours.",
    "Something looked back.",
    "Reality is tired of you.",
    "The impossible becomes mundane.",
    "You broke something. Not sure what.",
    "Even I didn't see that coming.",
    "The void giggles.",
  ],
  
  nothing: [
    "That word holds no power.",
    "You're guessing.",
    "Meaning requires intent.",
    "The void ignores you.",
    "Not everything is a word.",
    "Silence. Appropriate.",
    "The language rejects that.",
    "Try harder. Or don't.",
    "Nothing. Absolutely nothing.",
    "The universe shrugs.",
    "That meant less than nothing.",
    "Static. Just static.",
    "Even echoes need something to reflect.",
    "You're reaching. Stop reaching.",
    "Not even an echo.",
  ],

  meditation: [
    "The void recedes.",
    "Your mind clears.",
    "Peace. Briefly.",
    "The darkness lessens.",
    "You are centered.",
  ],
  
  discovery: [
    "You forced meaning into nothing.",
    "Interesting… that word responded.",
    "You're beginning to understand.",
    "The language grows.",
    "Another piece of the puzzle.",
    "The void accepts this one.",
    "A new word enters existence.",
    "You spoke. Something listened.",
    "The dictionary expands.",
    "That one has weight.",
    "Meaning crystallizes.",
    "The universe takes note.",
    "You're learning. Slowly.",
    "Another tool. Another danger.",
    "The language acknowledges you.",
  ],
  
  minor: [
    "Barely a ripple.",
    "Almost imperceptible.",
    "The universe yawns.",
    "A whisper of change.",
    "You'll barely notice.",
  ],
  
  major: [
    "That shook things.",
    "The ground trembles.",
    "Now you've done something.",
    "Significant. Very significant.",
    "The cosmos takes notice.",
  ],
  
  cosmic: [
    "The stars rearrange.",
    "Galaxies feel that.",
    "Cosmic scale consequences.",
    "You've touched the fabric.",
    "Gods would be impressed.",
  ],
  
  paradox: [
    "That shouldn't work. It did.",
    "Cause and effect weep.",
    "Logic takes damage.",
    "The universe is confused.",
    "Paradox accepted. Somehow.",
  ],
  
  warning: [
    "Careful now.",
    "You're playing with forces.",
    "The void watches closely.",
    "One more like that...",
    "Tread lightly.",
  ],
  
  curiosity: [
    "What was that?",
    "I didn't expect that.",
    "Fascinating. And terrifying.",
    "You surprised me.",
    "I'm almost impressed.",
  ],
  // Add to machineReactions object:
void: [
  "The void recoils.",
  "Something pushed back.",
  "The darkness thins.",
  "The void is afraid.",
  "It retreats. For now.",
],
reality: [
  "Reality solidifies.",
  "Things make sense again.",
  "The glitches fade.",
  "Stability returns.",
  "The universe corrects itself.",
],
// Add to machineReactions after existing arrays:

  universe: [
    "The universe breathes easier.",
    "Cosmic order restored. Briefly.",
    "The void releases its grip.",
    "Reality expands again.",
    "The stars shine brighter.",
    "Existence solidifies.",
    "The cosmos thanks you.",
    "Darkness retreats.",
    "Light returns.",
    "The universe remembers balance.",
    "Galaxies sigh with relief.",
    "Spacetime knits itself.",
    "The cosmic web strengthens.",
    "Distant worlds feel hope.",
    "The void shrinks.",
    "Creation wins. This time."
  ],

  void: [
    "The void recoils.",
    "Something pushed back.",
    "The darkness thins.",
    "The void is afraid.",
    "It retreats. For now.",
    "The void trembles.",
    "Darkness loses ground.",
    "Light pierces the void.",
    "The abyss blinks.",
    "Something noticed. Something fears you.",
    "The void whimpers.",
    "You pushed back the dark.",
    "The void hesitates.",
    "Your will overcomes."
  ],

  reality: [
    "Reality solidifies.",
    "Things make sense again.",
    "The glitches fade.",
    "Stability returns.",
    "The universe corrects itself.",
    "Physics remembers how to work.",
    "Existence stabilizes.",
    "The walls between worlds strengthen.",
    "Causality restored.",
    "Everything feels... real again."
  ],

  cosmic: [
    "The stars rearrange.",
    "Galaxies feel that.",
    "Cosmic scale consequences.",
    "You've touched the fabric.",
    "Gods would be impressed.",
    "The universe shudders.",
    "Creation notices you.",
    "Reality bends to your will.",
    "Cosmic forces acknowledge you.",
    "The void weeps."
  ]

};

export const voidMessages = [
  "The void watches.",
  "Something is counting your words.",
  "You feel eyes on your back.",
  "The terminal flickers.",
  "Your reflection doesn't blink.",
  "Shadows grow longer.",
  "The stars are rearranging.",
  "It knows your name now.",
  "You're not alone anymore.",
  "Behind you.",
  "It's learning from you.",
  "The darkness has depth.",
  "Something breathes in static.",
  "Your words echo back wrong.",
  "The void whispers your thoughts.",
  "It's getting closer.",
  "Don't turn around.",
  "It's in the room with you.",
  "The terminal shows someone behind you.",
  "You saw something. It saw you back."
];

export const transmissions = [
  "Mayday. Mayday. This is... static...",
  "They're in the walls. They're in the walls.",
  "Don't trust the silence.",
  "It's a lie. All of it.",
  "We found something. We shouldn't have.",
  "The signal keeps repeating. Help us.",
  "It's been 300 years. Are you still there?",
  "They look like us but they're not.",
  "The stars are going out one by one.",
  "We're the last ones. I think.",
  "If you get this, don't respond.",
  "It hears everything. Everything.",
  "There's something in the void with us.",
  "The language is alive. It's learning.",
  "We tried to learn. It learned us instead.",
  "Save yourselves. We're already gone.",
  "The transmissions are coming from inside.",
  "It's mimicking our voices now.",
  "Help us. Help us. Help us.",
  "We're sorry. We're so sorry."
];

export const playerThoughts = {
  pray: [
    "I looked in the mirror. I look pretty good.",
    "Please let this work.",
    "Just… help.",
    "I hope someone's listening.",
    "What am I even doing?",
    "Please don't let me fail.",
    "I'm trying my best here.",
    "If anyone's out there...",
    "Guide me. Or don't. Whatever.",
    "I believe in me. I think.",
    "The mirror lies. Or does it?",
    "My reflection nodded. That's new.",
    "Please. Just this once.",
    "Please, come back and do this for me",
    "Let me fix this.",
  ],
  
  meditate: [
    "I need to center myself.",
    "Clear your mind. Breathe.",
    "Focus on the void. Wait, not that.",
    "In... out... in... out...",
    "The silence helps.",
    "I can feel my thoughts settling.",
    "Just breathe.",
    "Maybe this will help.",
    "Peace. For a moment.",
    "The chaos fades, slightly.",
  ],
  
  read: [
    "Maybe this will make sense.",
    "I should've paid attention before.",
    "This is… complicated.",
    "The symbols blur together.",
    "I think I'm getting it.",
    "One word at a time.",
    "My eyes hurt.",
    "Knowledge takes time.",
    "Why didn't I study harder?",
    "This feels important.",
    "The pages burn into memory.",
    "I'll understand eventually.",
    "So many words...",
    "Each page hurts.",
    "Worth it. I hope.",
  ],
  
  idle: [
    "This feels wrong.",
    "Am I doing this right?",
    "I should slow down.",
    "Something is watching me.",
    "The silence is loud.",
    "What's that sound?",
    "I'm not alone here.",
    "The terminal hums.",
    "Did something move?",
    "Probably nothing.",
    "I should focus.",
    "So...I just type anything",
    "Is this what they wanted?",
    "The guardians left me here.",
    "Do I get paid?",
  ],
  
  sleep: [
    "I should rest for a bit.",
    "Just closing my eyes...",
    "Too tired to think.",
    "Five more minutes...",
    "Sleep sounds good.",
    "My mind needs a break.",
    "Just a short nap.",
    "The exhaustion hits.",
    "Can't keep my eyes open.",
    "Rest. Then continue.",
    "Dreams of stars.",
    "What if I don't wake up?",
    "Too tired to care.",
    "The void welcomes sleep.",
    "Just for a moment.",
  ],
  
  discovery: [
    "I found something!",
    "That's new.",
    "What does it mean?",
    "Another word learned.",
    "Progress. Finally.",
    "Yes! Got one.",
    "The language opens up.",
    "I did it.",
    "That felt right.",
    "One step closer.",
  ],
  
  failure: [
    "Nothing happened.",
    "Worth a try.",
    "Maybe next time.",
    "That was disappointing.",
    "I was sure that would work.",
    "Back to guessing.",
    "Why won't it work?",
    "This is harder than it looks.",
    "Frustrating.",
    "Try again. Always try again.",
  ],
  
  strain: [
    "My head hurts.",
    "Too much. Too fast.",
    "I need to stop.",
    "The pressure builds.",
    "Can't think straight.",
    "Everything blurs.",
    "Make it stop.",
    "Pushing too hard.",
    "Slow down. Breathe.",
    "This is too much.",
  ],
  
  observation: [
    "Interesting.",
    "So that's what that does.",
    "Noted.",
    "I'll remember that.",
    "Good to know.",
    "Dangerous. Useful.",
    "That could be helpful.",
    "Or harmful. Hard to tell.",
    "The universe is weird.",
    "Nothing is simple.",
  ],
  
  desperation: [
    "I can't fail.",
    "Not again.",
    "Please work.",
    "Anything. Please.",
    "I'm running out of time.",
    "The planet depends on me.",
    "No pressure.",
    "Why me?",
    "I didn't sign up for this.",
    "Someone else should be here.",
  ],
  
  hope: [
    "Maybe there's a way.",
    "I can do this.",
    "One day at a time.",
    "Getting better.",
    "I'm learning.",
    "Progress. Slow but steady.",
    "There's still time.",
    "It's not over yet.",
    "They depend on me",
    "For them...but mostly for me",
  ],
  
  confusion: [
    "What just happened?",
    "Did that work?",
    "I don't understand.",
    "That made no sense.",
    "Was that supposed to happen?",
    "I'm lost.",
    "None of this makes sense.",
    "The rules keep changing.",
    "Help? Anyone?",
    "I'm so confused.",
  ],
  
  victory: [
    "Yes! It worked!",
    "Finally!",
    "I did it!",
    "Not too shabby",
    "Success!",
    "One small step.",
    "Progress feels good.",
    "I'm not useless after all.",
    "Ha! Learned something new.",
    "Celebrate small wins.",
  ],
  
  regret: [
    "That was a mistake.",
    "Shouldn't have done that.",
    "Too late now.",
    "What have I done?",
    "Sorry. So sorry.",
    "I didn't mean to.",
    "If only I could undo...",
    "The guilt settles.",
    "Another scar.",
    "I can still fix this...I think",
  ],
  // Add to playerThoughts:

  universe: [
    "The stars look brighter.",
    "Maybe there's still time.",
    "The universe can heal.",
    "I feel less alone.",
    "Light persists.",
    "Not all is lost.",
    "Hope remains.",
    "The cosmos endures.",
    "I can feel it recovering.",
    "There's life out there. I know it."
  ],

  voidStruggle: [
    "The darkness is strong.",
    "I can feel it pressing in.",
    "Is this how it ends?",
    "I won't give up.",
    "The void won't win.",
    "I have to push back.",
    "This is harder than I thought.",
    "Every word matters.",
    "I can't let it consume everything.",
    "The void is patient. I have to be stronger."
  ],

  cosmicWonder: [
    "The scale of this is overwhelming.",
    "I'm just one person.",
    "How did I end up here?",
    "The guardians trusted me.",
    "I won't let them down.",
    "The universe is beautiful. Even now.",
    "Stars are dying and being born.",
    "I'm part of something bigger.",
    "This is terrifying and amazing.",
    "I need to focus."
  ],
  
  // NEW: Reality stability thoughts
  weirdness: [
    "Why are the controls not working?",
    "Everything looks... wrong.",
    "The letters won't stay still.",
    "Did that button just move?",
    "I can't focus on anything.",
    "The screen is rippling.",
    "My reflection just waved. I didn't.",
    "Something is wrong with reality.",
    "The buttons won't click right.",
    "I have to try twice for everything.",
    "The words are vibrating.",
    "This feels like a bad dream.",
    "Reality is unraveling.",
    "I can barely read this.",
    "The colors are all wrong.",
    "Is the terminal melting?",
    "I hear things that aren't there.",
    "My thoughts feel like someone else's.",
  ]
};

export function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}